//
//  Transactions.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Transactions: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _transactionId: String?
    var _amount: NSNumber?
    var _otherUserName: String?
    var _userId: String?
    var _userName: String?
    
    class func dynamoDBTableName() -> String {

        return "tipbucket-mobilehub-1564847731-Transactions"
    }
    
    class func hashKeyAttribute() -> String {

        return "_transactionId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_transactionId" : "transactionId",
               "_amount" : "amount",
               "_otherUserName" : "otherUserName",
               "_userId" : "userId",
               "_userName" : "userName",
        ]
    }
}
